/* *****************************************************************************************
*Autor: Nilton Cerqueira Bento de Oliveira Júnior
*Componente Curricular: MI-Programação 
*Concluido em: 05/02/2019
*Declaro que este código foi elaborado por mim de forma individual e não contém nenhum trecho 
*de código de outro colega ou de outro autor, tais como provindos de livros eapostilas, e 
*páginas ou documentos eletrônicos da Internet. Qualquer trecho de códigode outra autoria 
*que não a minha está destacado com uma citação para o autor e a fontedo código, e estou 
*ciente que estes trechos não serão considerados para fins de avaliação.
***************************************************************************************** */
package view;

import Controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author juniorlopes
 */
public class GUI extends javax.swing.JFrame {
    Controller controller;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        controller = new Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelMap = new javax.swing.JPanel();
        BaMap = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaCidades = new javax.swing.JList<>();
        labelCidades = new javax.swing.JLabel();
        labelRoteiro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaRoteiro = new javax.swing.JList<>();
        bntCalcular = new javax.swing.JButton();
        btnLimparRota = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        labelConsumo = new javax.swing.JLabel();
        textConsumo = new javax.swing.JTextField();
        labelPrecoGas = new javax.swing.JLabel();
        textGas = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        importMap = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenu();
        credito = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Roteiro");
        setResizable(false);

        MainPanel.setPreferredSize(new java.awt.Dimension(670, 550));

        PanelMap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PanelMapMouseReleased(evt);
            }
        });

        BaMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ba (2).png"))); // NOI18N

        javax.swing.GroupLayout PanelMapLayout = new javax.swing.GroupLayout(PanelMap);
        PanelMap.setLayout(PanelMapLayout);
        PanelMapLayout.setHorizontalGroup(
            PanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BaMap)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        PanelMapLayout.setVerticalGroup(
            PanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BaMap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ListaCidades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ListaCidadesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(ListaCidades);

        labelCidades.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCidades.setText("Cidades:");

        labelRoteiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelRoteiro.setText("Roteiro:");

        listaRoteiro.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaRoteiro);

        bntCalcular.setBackground(new java.awt.Color(51, 51, 255));
        bntCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntCalcular.setText("Calcular Rota");
        bntCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularActionPerformed(evt);
            }
        });

        btnLimparRota.setBackground(new java.awt.Color(255, 51, 51));
        btnLimparRota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparRota.setText("Limpar Rota");
        btnLimparRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparRotaActionPerformed(evt);
            }
        });

        btnCadastro.setBackground(new java.awt.Color(51, 51, 255));
        btnCadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastro.setText("Cadastrar Dados");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        labelConsumo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelConsumo.setText("Consumo (carro) em Km/l:");

        labelPrecoGas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPrecoGas.setText("Preço da Gasolina:");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(PanelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimparRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(labelCidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRoteiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textConsumo)
                    .addComponent(labelPrecoGas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textGas))
                .addGap(22, 22, 22))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(labelCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRoteiro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparRota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConsumo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPrecoGas)
                        .addGap(4, 4, 4)
                        .addComponent(textGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastro)
                        .addGap(34, 34, 34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        file.setText("Arquivo");

        importMap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        importMap.setText("Importar Mapa");
        importMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importMapActionPerformed(evt);
            }
        });
        file.add(importMap);

        jMenuBar1.add(file);

        sobre.setText("sobre");

        credito.setText("créditos");
        credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoActionPerformed(evt);
            }
        });
        sobre.add(credito);

        ajuda.setText("ajuda");
        ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaActionPerformed(evt);
            }
        });
        sobre.add(ajuda);

        jMenuBar1.add(sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Evento para adicionar o mapa
     * @param evt 
     */
    private void importMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importMapActionPerformed
        controller.importMap(PanelMap,ListaCidades,listaRoteiro); // O método era aqui
    }//GEN-LAST:event_importMapActionPerformed
    /**
     * evento para mostrar os créditos
     * @param evt 
     */
    private void creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoActionPerformed
        JOptionPane.showMessageDialog(null, "Feito por Júnior Lopes e João Pedro");
    }//GEN-LAST:event_creditoActionPerformed
    /**
     * evento para calcular a rota
     * @param evt 
     */
    private void bntCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularActionPerformed
        controller.acharMenorCaminho();
    }//GEN-LAST:event_bntCalcularActionPerformed
    /**
     * evento para limpar a rota escolhida pelo usuário
     * @param evt 
     */
    private void btnLimparRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparRotaActionPerformed
        controller.limparRoteiro(listaRoteiro, PanelMap);
    }//GEN-LAST:event_btnLimparRotaActionPerformed
    /**
     * evento para cadastrar o consumo e preço da gasolina
     * @param evt 
     */
    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
       controller.cadastrarDados(textConsumo, textGas);
    }//GEN-LAST:event_btnCadastroActionPerformed
    /**
     * evento da ajuda
     * @param evt 
     */
    private void ajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaActionPerformed
        JOptionPane.showMessageDialog(null, "1 - Importe um mapa no padrão desejado\n2 - Insira os dados no "
                + "canto inferior direito\n3 - Selecione no mapa ou na lista as cidades que precisa ir,"
                + " se preciso, limpe o roteiro");
    }//GEN-LAST:event_ajudaActionPerformed
    /**
     * evento para adicionar uma cidade ao roteiro a partir da lista
     * @param evt 
     */
    private void ListaCidadesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaCidadesMouseReleased
        controller.addRoteirto(listaRoteiro,ListaCidades.getSelectedValue(), PanelMap);
    }//GEN-LAST:event_ListaCidadesMouseReleased
    /**
     * evento para adicionar uma cidade ao roteiro a partir do mapa
     * @param evt 
     */
    private void PanelMapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMapMouseReleased
        controller.reconhecerCidadeClicada(PanelMap, evt.getX(), evt.getY(), listaRoteiro);
    }//GEN-LAST:event_PanelMapMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaMap;
    private javax.swing.JList<String> ListaCidades;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelMap;
    private javax.swing.JMenuItem ajuda;
    private javax.swing.JButton bntCalcular;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnLimparRota;
    private javax.swing.JMenuItem credito;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem importMap;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCidades;
    private javax.swing.JLabel labelConsumo;
    private javax.swing.JLabel labelPrecoGas;
    private javax.swing.JLabel labelRoteiro;
    private javax.swing.JList<String> listaRoteiro;
    private javax.swing.JMenu sobre;
    private javax.swing.JTextField textConsumo;
    private javax.swing.JTextField textGas;
    // End of variables declaration//GEN-END:variables
}
